### PR TITLE
implemented rebrandable OLS with environment variables for #438

### PR DESCRIPTION
**Pull request by giraygi**
Current debranding feature disables the use of some functionalities. For this reason, I have introduced a new variable to be able to hide some EBI specific content. Plus, I have introduced several branding variables for adapting some page content to the identity of another institution willing to maintain the service. These variables can be assigned to the docker-compose file as environment variables.

### CODE REVIEW

**Comment by matentzn** [comment]
Super cool @giraygi, do you have a public instance somewhere where I can see how your changes look like life? I am not directly on the OLS team, but interested in your changes for some of our custom OLS projects.

**Comment by giraygi** [comment]
> Super cool @giraygi, do you have a public instance somewhere where I can see how your changes look like life? I am not directly on the OLS team, but interested in your changes for some of our custom OLS projects.

Thanks a lot @matentzn . We have two public instances to give you an idea about my changes. They are: [TS of NFDI4Ing](https://service.tib.eu/ts4ing/index) and [TS of TIB Central](https://service.tib.eu/ts4tib/index). The footer is not very fancy yet since I wanted to stick to the code of EBI OLS as much as possible but I will update it soon once my changes are approved. Plus, this rebranding currently excludes favicons. I will also add it later.

**Comment by matentzn** [comment]
This is really amazing! :) Nice job!

**Comment by udp** [comment]
This is great, thank you! I will get it merged this week. 😃

**Comment by giraygi** [comment]
Thanks a lot guys!  I am very glad that I might be of any help :)

**Comment by giraygi** [comment]
@udp Hello again. I wanted to remind you that I had made a few corrections (4 more commits on 2nd of June ) after you confirmed my pull request.

**Review by udp — APPROVED** [review]

**Comment by udp** [comment]
Thanks!

**Comment by giraygi** [comment]
> Thanks!

No Problem! I have a small bug-fix and documentation added for this in https://github.com/EBISPOT/OLS/pull/516

**Pull request merged**
