### PR TITLE
Include SOLR config within docker image

### PR DESCRIPTION
**Pull request by johannes-darms**
closes https://github.com/EBISPOT/OLS/issues/407

### CODE REVIEW

**Comment by udp** [comment]
Thanks!

**Comment by johannes-darms** [comment]
> Thanks!

You're welcome! Is there a release/update plan for the [image on docker hub](https://hub.docker.com/r/ebispot/ols-solr) ?

**Comment by udp** [comment]
It's now been pushed to Docker Hub.  I also moved the config into the solr/ directory and updated the docker compose file to use ols-solr from docker hub rather than building from the solr/ directory.

**Comment by matentzn** [comment]
Does this introduce a breaking change from the previous version?

**Comment by udp** [comment]
No, because you can still mount a config over the /mnt/solr-config directory if you so desire.

**Comment by matentzn** [comment]
thanks @udp

**Comment by johannes-darms** [comment]
Thanks! Works like charm! Please find attached my compose file, with that I can deploy an OLS instance without access to the source code. 

```
version: '2'
services:
    ols-solr:
        image: ebispot/ols-solr:latest
        environment:
          - SOLR_HOME=/mnt/solr-config
        ports:
          - 8983:8983
        volumes:
          - ols-solr-data:/var/solr
        command: ["-Dsolr.solr.home=/mnt/solr-config", "-Dsolr.data.dir=/var/solr", "-f"]
    ols-mongo:
      image: mongo:3.2.9
      ports:
          - 27017:27017
      volumes:
          - ols-mongo-data:/data/db
      command:
          - mongod
    ols-web:
      image: ebispot/ols-web:stable
      depends_on:
        - ols-solr
        - ols-mongo
      links:
        - ols-solr:solr
        - ols-mongo:mongo
      environment:
        - spring.data.solr.host=http://solr:8983/solr
        - spring.data.mongodb.host=mongo
        - OLS_HOME=/mnt/
        - ols.customisation.debrand=true
        - ols.customisation.org="ORG"
        - ols.customisation.title="TITLE LONG"
        - ols.customisation.short-title="SHORT_TITLE"
      volumes:
        - ols-neo4j-data:/mnt/neo4j
      ports:
      - 8080:8080
volumes:
    ols-solr-data:
        external: true
    ols-mongo-data:
        external: true
    ols-neo4j-data:
        external: true
```

**Comment by matentzn** [comment]
Thanks for sharing that @johannes-darms 

I am also working on a project using compose to deploy OLS/OXO/Zooma. The config looks mostly like yours, but, can I ask, what exactly does the colon mean in the `links` section? `- ols-solr:solr`?

Note that you can also add a custom logo like that:

```
environment:
        ...
        - ols.customisation.debrand=true
        - ols.customisation.logo=/custom/ihcc.png
        ...
      volumes:
        ...
        - ./config/ols-config/ihcc.png:/mnt/web-custom/ihcc.png
```

**Comment by johannes-darms** [comment]
Thanks, I didn't now that! 

That`s an [alias](https://docs.docker.com/compose/compose-file/#links). The linked container name is `ols-solr` and there I define an alias `solr`. So both names can be used to access the container.

**Comment by matentzn** [comment]
Perfect! Thank you! :)

**Comment by johannes-darms** [comment]
Are there any plans to migrate from a embedded OLS to a dedicated remote instance?

**Comment by matentzn** [comment]
It think this is on the agenda for midterm, but not short term, right @udp ?

**Comment by udp** [comment]
It is definitely something we want to do, hopefully in the 4.x release.

**Pull request merged**
